### ISSUE TITLE
你好 223.8836.35什么时候可以更新啊

### ISSUE THREAD

**Issue by jayjd** [sgpublic/lombok-plugin-action#1]
[223.8836.35](https://github.com/sgpublic/lombok-plugin-repository/releases/tag/223.8836.35)

**Comment by sgpublic** [comment]
JetBrains IDEA v223.8836.35 目前在官方渠道下载不到，所以没法导出 lombok 插件

**Comment by jayjd** [comment]
> JetBrains IDEA v223.8836.35 目前在官方渠道下载不到，所以没法导出 lombok 插件

https://developer.android.google.cn/studio/preview
可以下载到啊！
![image](https://user-images.githubusercontent.com/15134709/229692880-926f4e27-90d2-44e4-8fb5-2d8a8cf37c88.png)

**Comment by sgpublic** [comment]
是IDEA不是Android Studio

**Comment by jayjd** [comment]
> 是IDEA不是Android Studio

你更新的不就是android studio的插件吗 
不是很懂 。。。

**Comment by sgpublic** [comment]
插件是从Android Studio对应版本的IDEA Ultimate导出的

**Comment by xianzheTM** [comment]
> 插件是从Android Studio对应版本的IDEA Ultimate导出的

[IntelliJ-IDEA-2022.3-Latest-Builds](https://youtrack.jetbrains.com/articles/IDEA-A-236159435/IntelliJ-IDEA-2022.3-Latest-Builds。)你好，这里有223.8836.41，可以使用吗？必须严格匹配这个编号吗？

**Comment by sgpublic** [comment]
> [IntelliJ-IDEA-2022.3-Latest-Builds](https://youtrack.jetbrains.com/articles/IDEA-A-236159435/IntelliJ-IDEA-2022.3-Latest-Builds%E3%80%82)你好，这里有223.8836.41，可以使用吗？必须严格匹配这个编号吗？

据我所知，IDEA 中内置的 Lombok 插件在不做任何修改的情况下，只适用于当前版本，因此如果要在不做任何修改的情况下导出适用于 Android Studio 的插件，版本名就必须完全一致；

如果修改其信息可以强行使其适用于其他版本，但是可能会出现不可预知的适配问题，因此这不在本仓库的考虑范围内；

而目前为止所有正式版都有其对应公开发布的 IDEA 版本，所以推荐使用正式版 Android Studio。
