### ISSUE TITLE
经测试 223.8836.41 适用于以下版本

### ISSUE THREAD

**Issue by jayjd** [sgpublic/lombok-plugin-action#2]
[223.8836.35](https://github.com/sgpublic/lombok-plugin-repository/releases/tag/223.8836.35)
Android Studio Hedgehog | 2023.1.1 Canary 1
Android Studio Giraffe | 2022.3.1 Beta 1
Android Studio Giraffe | 2022.3.1 Canary 11
Android Studio Giraffe | 2022.3.1 Canary 10

**Comment by jayjd** [comment]
[223.8836.41 点击下载 lombok.zip](https://github.com/sgpublic/lombok-plugin-repository/files/11349492/lombok.zip)

注：
**无需修改版本号**

**Comment by sgpublic** [comment]
...你咋测试的，无论是你的 zip 还是我刚手动从 223.8836.41 导出来的 jar 都没办法在设置里安装到 223.8836.35，你要说手动直接放到 plugins 文件夹那确实没问题，无论什么版本都能装，但是这就不在本仓库的职责范围内了，本仓库想要做到的是可以检查更新，随 Android Studio 升级而升级，且绝对的版本兼容性。

**Comment by sgpublic** [comment]
新的解决方案已可用：[README.md](https://github.com/sgpublic/lombok-plugin-repository/blob/repository/README.md)
