### ISSUE TITLE
fork后无法运行action

### ISSUE THREAD

**Issue by QAQQL** [sgpublic/lombok-plugin-action#3]
已配置TOKEN,运行到
 - name: Check update
      env:
        TOKEN: ${{ secrets.TOKEN }}
        REPO: 'sgpublic/lombok-plugin-action'
      run: |
        cd /workdir
        ./action -token $TOKEN -repo $REPO
提示./action无此 -token 用法

**Comment by sgpublic** [comment]
action 用法已弃用

**Comment by sgpublic** [comment]
action 用法已弃用

**Comment by QAQQL** [comment]
那是需要自己clone到本地,配置config.yaml运行是嘛

**Comment by sgpublic** [comment]
用法来讲是这样，不过这个仓库 release 里就是运行结果的说

**Comment by QAQQL** [comment]
好的,谢谢您
