### ISSUE TITLE
Add support for Android Studio Giraffe 2023.3.1

### ISSUE THREAD

**Issue by Phanquan** [sgpublic/lombok-plugin-action#4]
As the title said, the current version doesn't support the new android studio update.
Thanks

**Comment by sgpublic** [comment]
I really didn't expect that Google would use an unpublished version of IDEA, soon new solutions will be available (under construction: [a67a5b406c66c7c24efbb9dc9cc6862305ab67f3](https://github.com/sgpublic/lombok-plugin-repository/commit/a67a5b406c66c7c24efbb9dc9cc6862305ab67f3)).

As a temporary solution, you can manually install the zip just uploaded in this release [223.8836.3](https://github.com/sgpublic/lombok-plugin-repository/releases/tag/223.8836.35).

#2

**Comment by sgpublic** [comment]
I really didn't expect that Google would use an unpublished version of IDEA, soon new solutions will be available (under construction: [a67a5b406c66c7c24efbb9dc9cc6862305ab67f3](https://github.com/sgpublic/lombok-plugin-repository/commit/a67a5b406c66c7c24efbb9dc9cc6862305ab67f3)).

As a temporary solution, you can manually install the zip just uploaded in this release [223.8836.35](https://github.com/sgpublic/lombok-plugin-repository/releases/tag/223.8836.35).

#2

**Comment by Phanquan** [comment]
Thanks, It fixed this issue.

**Comment by sgpublic** [comment]
new solution is now available: [README.EN.md](https://github.com/sgpublic/lombok-plugin-repository/blob/repository/README.EN.md)
