### ISSUE TITLE
Support for Android Studio 2023.2.1

### ISSUE THREAD

**Issue by jfoder** [sgpublic/lombok-plugin-action#5]
Currently Android Studio 2023.2.1 has no Lombok plugin, need to release version supporting that build.

**Comment by sgpublic** [comment]
Hi, I downloaded and tested the 14 Canary versions of Android Studio Iguana, and all versions were able to download the Lombok plugin provided by `JetBrains s.r.o.` directly from the plugin store without any configuration, just as the [README.md](https://github.com/sgpublic/lombok-plugin-repository/blob/5de4d2e9f5b120c6878cbf17292f82ef69a1580f/README.EN.md?plain=1#L7) says. A screenshot of one of the version tests is as follows:

![image](https://github.com/sgpublic/lombok-plugin-repository/assets/37202870/d65c258a-10d8-42a4-94c1-30b450fcb14f)

May I ask what the specific version name of the Android Studio 2023.2.1 you are using is? It should be a version name like "#AI-232.9921.47.2321.10840167".

**Comment by sgpublic** [comment]
Since I haven't received your reply for a long time, I'm sorry that I will close this issue. If you have other information to provide, please reopen this issue.
