### ISSUE TITLE
Add support for Android Studio Hedgehog | 2023.1.1

### ISSUE THREAD

**Issue by Phanquan** [sgpublic/lombok-plugin-action#6]
Google did it again, breaking stuffs...

**Comment by sgpublic** [comment]
Roger that, but this may just be a lag in the plugin upload. Anyway, I will add the version that is not supported by the plugin store.

**Comment by sgpublic** [comment]
I have added version [231.9392.1](https://github.com/sgpublic/lombok-plugin-repository/wiki/231.9392.1) support, you can use `https://raw.githubusercontent.com/sgpublic/lombok-plugin-repository/repository/full` to subscribe.

The version information of 231.9392.1 in `https://raw.githubusercontent.com/sgpublic/lombok-plugin-repository/repository/release` will be added after Google adds the release version of Android Studio Hedgehog | 2023.1.1 to the version subscription. I guess it won't be long.
